version: '3'

services:
    db:
        container_name: postgres_database
        image: postgres:15.1
        volumes:
#            - postgres-db:/var/lib/postgresql/data
            - ./postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=123456
            
    pgAdmin:
        container_name: pgadmin
        image: dpage/pgadmin4:6.17
        depends_on:
            - db
        ports:
            - "8080:80"
        volumes:
            - ./pgadmin:/var/lib/pgadmin
        environment:
            - PGADMIN_DEFAULT_PASSWORD=123456
            - PGADMIN_DEFAULT_EMAIL=jesus@email.com

#volumes:
#    postgres-db:
#        external: true